Bashrc

diff --git a/installscript b/installscript
--- a/installscript
+++ b/installscript
@@ -11,15 +11,28 @@ ln -sf $HOME/.dotfiles/macos/.mackup.cfg $HOME/.mackup.cfg
 ln -sf $HOME/.dotfiles/macos/.mackup $HOME/.mackup
 
 ln -sf $HOME/.dotfiles/shell/.bash_profile $HOME/.bash_profile
+ln -sf $HOME/.dotfiles/shell/.bash_profile $HOME/.bashrc
 
 pushd $HOME/.dotfiles
 
 echo 'Install composer'
 echo '----------------'
+cd ~/.dotfiles
+
+EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
 php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
-php -r "if (hash_file('SHA384', 'composer-setup.php') === '93b54496392c062774670ac18b134c3b3a95e5a5e5c8f1a9f115f203b75bf9a129d5daa8ba6a13e2cc8a1da0806388a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
-php composer-setup.php
-php -r "unlink('composer-setup.php');"
+ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+
+if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
+then
+    >&2 echo 'ERROR: Invalid installer signature'
+    rm composer-setup.php
+    exit 1
+fi
+
+php composer-setup.php --quiet
+rm -f composer-setup.php
+
 echo 'move composer to /usr/local/bin/composer'
 mv -f composer.phar /usr/local/bin/composer
 
